
name: Live Review Screenshot Bot

on:

  workflow_dispatch:

  schedule:
    - cron: "0 4-11 * * *"

jobs:

  screenshot-job:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          pip install selenium
          pip install webdriver-manager
          pip install mysql-connector-python

      - name: Run Bot
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          TRADINGVIEW_COOKIES: ${{ secrets.TRADINGVIEW_COOKIES }}

        run: |
          python livescreen.py
