
name: StockEdge News Scraper

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

jobs:
  scrape-news:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          pip install selenium
          pip install webdriver-manager
          pip install mysql-connector-python

      - name: Run Script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        run: python stockedgenews.py

